1. Preprocessing And Cleaning
2. TRAIN TEST SPLIT
3. BOW AND TFI-IDF (SENTENCE------>VECTORS) **{PREVENTING DATA LEAKAGE}**
4. TRAINED OUR MODEL

In [1]:
import pandas as pd

In [2]:
messages = pd.read_csv(r"C:\Users\vikas\OneDrive\Desktop\Machine Learning\NLP FOR MACHINE LEARNING\spam.csv", encoding='ISO-8859-1')

In [3]:
messages

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [4]:
messages.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [5]:
messages.drop(columns=['Unnamed: 2'], inplace=True)

In [6]:
messages.drop(columns=['Unnamed: 3'], inplace=True)

In [7]:
messages.drop(columns=['Unnamed: 4'], inplace=True)

In [8]:
messages

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [9]:

messages.rename(columns={'v1': 'label', 'v2': 'message'}, inplace=True)
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

### **Data Cleaning And Preprocessing**

In [10]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem import PorterStemmer
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [11]:
corpus = [ ]
for i in range(0,len(messages)):
    review = re.sub('[^a-zA-z]',' ',messages['message'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [12]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [13]:
## Output Features
y = pd.get_dummies(messages['label'])

In [14]:
y = y.iloc[:,0].values

In [15]:
y.shape

(5572,)

In [16]:
from sklearn.model_selection import train_test_split
X_train , X_test, y_train, y_test = train_test_split(corpus,y,test_size=0.20)

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
cv = CountVectorizer(max_features=2500,ngram_range=(1,2))

In [19]:
len(X_train),len(y_train)

(4457, 4457)

In [20]:
X_train = cv.fit_transform(X_train).toarray()
X_test = cv.transform(X_test).toarray()

In [21]:
import numpy as np
np.set_printoptions(edgeitems=300,linewidth=100000,formatter=dict(float=lambda x : "%.3g" % x))

In [22]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [23]:
X_test

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [24]:
cv.vocabulary_

{'whatev': 2391,
 'im': 983,
 'pretti': 1628,
 'piss': 1565,
 'gal': 746,
 'sch': 1792,
 'stuff': 1998,
 'come': 374,
 'got': 828,
 'sound': 1923,
 'like': 1144,
 'could': 424,
 'lot': 1192,
 'time': 2119,
 'spent': 1937,
 'boy': 197,
 'grin': 845,
 'take': 2037,
 'good': 814,
 'dog': 541,
 'go': 787,
 'nice': 1420,
 'long': 1176,
 'bath': 138,
 'sound like': 1924,
 'wait': 2316,
 'till': 2118,
 'bu': 216,
 'pick': 1559,
 'wait till': 2324,
 'yeah': 2481,
 'imagin': 984,
 'would': 2442,
 'realli': 1694,
 'gentl': 762,
 'doc': 538,
 'treat': 2173,
 'hey': 908,
 'happen': 881,
 'de': 488,
 'alright': 53,
 'didnt': 514,
 'holla': 939,
 'done': 545,
 'hand': 878,
 'celebr': 294,
 'full': 738,
 'swing': 2033,
 'yet': 2488,
 'right': 1743,
 'second': 1799,
 'gotta': 836,
 'hit': 922,
 'peopl': 1540,
 'first': 689,
 'number': 1450,
 'gonna': 812,
 'pain': 1519,
 'ass': 98,
 'rather': 1680,
 'get': 763,
 'possibl': 1608,
 'tell': 2063,
 'pleas': 1579,
 'walk': 2329,
 'bcoz': 142,
 'want': 2336

In [25]:
from sklearn.naive_bayes import MultinomialNB

In [26]:
spam_detect_model = MultinomialNB().fit(X_train,y_train)

In [27]:
spam_detect_model

MultinomialNB()

In [28]:
y_pred = spam_detect_model.predict(X_test)

In [29]:
from sklearn.metrics import accuracy_score,classification_report

In [30]:
accuracy_score(y_test,y_pred)

0.9811659192825112

In [31]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.94      0.91      0.93       149
        True       0.99      0.99      0.99       966

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



# **TF-IDF**

In [32]:
from sklearn.model_selection import train_test_split
X_train , X_test, y_train, y_test = train_test_split(corpus,y,test_size=0.20)

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [34]:
tfidf = TfidfVectorizer(max_features=2500,ngram_range=(1,2))

In [35]:
X_train = tfidf.fit_transform(X_train).toarray()
X_test = tfidf.fit_transform(X_test).toarray()

In [36]:
import numpy as np
np.set_printoptions(edgeitems=300,linewidth=100000,formatter=dict(float=lambda x : "%.3g" % x))

In [37]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [38]:
tfidf.vocabulary_

{'librari': 878,
 'hope': 755,
 'dont': 430,
 'randomli': 1456,
 'reformat': 1600,
 'randomli reformat': 1457,
 'ful': 600,
 'song': 2092,
 'nope': 1092,
 'go': 627,
 'home': 751,
 'petrol': 1351,
 'lor': 916,
 'like': 886,
 'rain': 1439,
 'soon': 2095,
 'go home': 629,
 'jesu': 807,
 'bitch': 137,
 'tri': 2291,
 'give': 625,
 'drug': 446,
 'answer': 53,
 'fuck': 599,
 'phone': 1352,
 'today': 2261,
 'meet': 971,
 'town': 2285,
 'ju': 819,
 'take': 2172,
 'mrt': 1037,
 'later': 852,
 'escap': 485,
 'theatr': 2223,
 'watch': 2403,
 'kavalan': 822,
 'minut': 992,
 'escap theatr': 486,
 'theatr go': 2224,
 'go watch': 639,
 'watch kavalan': 2405,
 'kavalan minut': 823,
 'floor': 563,
 'even': 495,
 'shirt': 2042,
 'sometim': 2090,
 'open': 1259,
 'mouth': 1028,
 'come': 296,
 'flow': 564,
 'dream': 441,
 'world': 2459,
 'without': 2447,
 'half': 698,
 'time': 2245,
 'joy': 816,
 'lot': 920,
 'tv': 2302,
 'show': 2047,
 'see': 2006,
 'guess': 689,
 'thing': 2228,
 'must': 1052,
 'done': 42

In [39]:
from sklearn.naive_bayes import MultinomialNB

In [40]:
spam_tfidf_model = MultinomialNB().fit(X_train,y_train)

In [41]:
spam_tfidf_model

MultinomialNB()

In [42]:
y_pred = spam_tfidf_model.predict(X_test)

In [43]:
from sklearn.metrics import accuracy_score,classification_report

In [44]:
accuracy_score(y_test,y_pred)

0.7874439461883408

In [45]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.31      0.32      0.31       168
        True       0.88      0.87      0.87       947

    accuracy                           0.79      1115
   macro avg       0.59      0.60      0.59      1115
weighted avg       0.79      0.79      0.79      1115



In [46]:
print("The End")

The End
